# Generated by Django 3.1.5 on 2021-01-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20210111_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picture',
            new_name='image',
        ),
    ]
